
export const GET_TODOS_ACTION = "GET_TODOS_ACTION";
export const GET_TODOS_ACTION_FAIL = "GET_TODOS_ACTION_FAIL"
export const CREATE_TODO_ACTION = "CREATE_TODO_ACTION"
export const CREATE_TODO_ACTION_FAIL = "CREATE_TODO_ACTION_FAIL"
export const UPDATE_TODO_ACTION = "UPDATE_TODO_ACTION";
export const UPDATE_TODO_ACTION_FAIL = "UPDATE_TODO_ACTION_FAIL";
export const DELETE_TODO_ACTION = "DELETE_TODO_ACTION";
export const DELETE_TODO_ACTION_FAIL = "DELETE_TODO_ACTION_FAIL";
