const GET_TODOS_ACTION = "GET_TODOS_ACTION";
const GET_TODOS_ACTION_FAIL = "GET_TODOS_ACTION_FAIL"
const CREATE_TODO_ACTION = "CREATE_TODO_ACTION"
const CREATE_TODO_ACTION_FAIL = "CREATE_TODO_ACTION_FAIL"
const UPDATE_TODO_ACTION = "UPDATE_TODO_ACTION";
const UPDATE_TODO_ACTION_FAIL = "UPDATE_TODO_ACTION_FAIL";
const DELETE_TODO_ACTION = "DELETE_TODO_ACTION";
const DELETE_TODO_ACTION_FAIL = "DELETE_TODO_ACTION_FAIL"   